build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-adc"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-lowpower"
    - PLATFORMIO_PROJECT_DIR: "examples/PingPong"
    - PLATFORMIO_PROJECT_DIR: "examples/LoRaWAN"
    - PLATFORMIO_PROJECT_DIR: "examples/LoRaWAN_Interrupt"

platform:
  - x64
install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=C:\Python37\Scripts;%PATH%
  - cmd: pip3 install platformio
  - cmd: pio update
  - cmd: pio platform install file://.

test_script:
  - cmd: pio run -d %PLATFORMIO_PROJECT_DIR%
