build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-adc"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-lowpower"
    - PLATFORMIO_PROJECT_DIR: "examples/arduino-rgb"
    - PLATFORMIO_PROJECT_DIR: "examples/LoRa/LoRaBasic/PingPong"
    - PLATFORMIO_PROJECT_DIR: "examples/LoRa/LoRaWAN/LoRaWAN"
    - PLATFORMIO_PROJECT_DIR: "examples/LoRa/LoRaWAN/LoRaWAN_Interrupt"

install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=C:\Python36\Scripts;%PATH%
  - cmd: pip3 install -U https://github.com/platformio/platformio/archive/develop.zip
  - cmd: platformio platform install file://.

test_script:
  - cmd: platformio run -s -d %PLATFORMIO_PROJECT_DIR%
